In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Markdown, display, HTML

# Fix the dying kernel problem (only a problem in some installations - you can remove it, if it works without it)
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

# Numpy tasks

For a detailed reference check out: https://numpy.org/doc/stable/reference/arrays.indexing.html.

**Task 1.** Calculate the sigmoid (logistic) function on every element of the following numpy array [0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25] and print the last 5 elements. Use only vector operations.

In [2]:
# Write your code here
x = np.array([0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25])
sig = 1 / (1 + np.exp(-x))
print(sig[-5:])

[0.549834   0.47502081 0.52497919 0.68997448 0.4378235 ]


**Task 2.** Calculate the dot product of the following two vectors:<br/>
$x = [3, 1, 4, 2, 6, 1, 4, 8]$<br/>
$y = [5, 2, 3, 12, 2, 4, 17, 11]$<br/>
a) by using element-wise mutliplication and np.sum,<br/>
b) by using np.dot,<br/>
b) by using np.matmul and transposition (y.reshape(-1, 1), the alternative y.T will not work because T does not work on 1D arrays).

In [3]:
# Write your code here
x = np.array([3,1,4,2,6,1,4,8])
y = np.array([5,2,3,12,2,4,17,11])

# a)
dot1 = np.sum(x*y)
print(dot1)

# b)
dot2 = np.dot(x, y)
print(dot2)

# c)
dot3 = np.matmul(x, y)
print(dot3)

225
225
225


**Task 3.** Calculate value of the logistic model<br/>
$$y = \frac{1}{1 + e^{-x_0 \theta_0 - \ldots - x_9 \theta_9 - \theta_{10}}}$$
for<br/>
$x = [1.2, 2.3, 3.4, -0.7, 4.2, 2.7, -0.5, 1.4, -3.3, 0.2]$<br/>
$\theta = [2.7, 0.33, -2.12, -1.73, 2.9, -5.8, -0.9, 12.11, 3.43, -0.5, -1.65]$<br/>
and print the result. Use only vector operations.

In [4]:
# Write your code here
x = np.array([1.2,2.3,3.4,-0.7,4.2,2.7,-0.5,1.4,-3.3,0.2,1.0])
theta = np.array([2.7,0.33,-2.12,-1.73,2.9,-5.8,-0.9,12.11,3.43,-0.5,-1.65])
y = 1 / (1 + np.exp(-np.dot(x, theta)))
print(y)

0.24176998326155735


**Task 4.** Calculate value of the multivariate linear regression model<br/>
$$y = A x + B$$
for<br/>
$A = \begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \end{bmatrix}$<br/>
$B = \begin{bmatrix} 0.2 \\ 0.3 \end{bmatrix}$<br/>
$x = [1, 2, 3]^T$<br/>
and print the result. Use only vector and matrix operations.

In [5]:
# Write your code here
A = np.array([
    [1, 2, 1],
    [3, 0, 1]
])

B = np.array([
    [0.2],
    [0.3]
])

x = np.array([[1],[2],[3]])

y = np.matmul(A, x) + B
print(y)


[[8.2]
 [6.3]]


# Pandas

## Load datasets

- Steam (https://www.kaggle.com/tamber/steam-video-games)

- MovieLens (https://grouplens.org/datasets/movielens/)

In [6]:
steam_df = pd.read_csv(os.path.join("data", "steam", "steam-200k.csv"), 
                       names=['user-id', 'game-title', 'behavior-name', 'value', 'zero'])

ml_ratings_df = pd.read_csv(os.path.join("data", "movielens_small", "ratings.csv"))
ml_movies_df = pd.read_csv(os.path.join("data", "movielens_small", "movies.csv"))

## Merge both MovieLens DataFrames into one

In [7]:
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
steam_df.head(10)

user-id                  game-title behavior-name  value  zero
0  151603712  The Elder Scrolls V Skyrim      purchase    1.0     0
1  151603712  The Elder Scrolls V Skyrim          play  273.0     0
2  151603712                   Fallout 4      purchase    1.0     0
3  151603712                   Fallout 4          play   87.0     0
4  151603712                       Spore      purchase    1.0     0
5  151603712                       Spore          play   14.9     0
6  151603712           Fallout New Vegas      purchase    1.0     0
7  151603712           Fallout New Vegas          play   12.1     0
8  151603712               Left 4 Dead 2      purchase    1.0     0
9  151603712               Left 4 Dead 2          play    8.9     0

## Pandas tasks - Steam dataset

**Task 5.** How many people made a purchase in the Steam dataset? Remember that a person could buy many games, but you need to count every person once.

In [8]:
# Write your code here
result = steam_df.loc[(steam_df['behavior-name'] == 'purchase'), ['user-id']]
result = result.drop_duplicates()
print(len(result))

12393


**Task 6.** How many people made a purchase of "The Elder Scrolls V Skyrim"?

In [9]:
# Write your code here
result = steam_df.loc[((steam_df['game-title'] == 'The Elder Scrolls V Skyrim') & (steam_df['behavior-name'] == 'purchase'))]
print(len(result))

717


**Task 7.** How many purchases people made on average?

In [10]:
# Write your code here
results = steam_df.loc[(steam_df['behavior-name'] == 'purchase'), ['user-id', 'behavior-name']]
results_grupped = results.groupby('user-id').count()
s1 = np.sum(results_grupped['behavior-name'])
s2 = steam_df.loc[:, ['user-id']].drop_duplicates()
print(round(s1 / len(s2), 2))

10.45


**Task 8.** Who bought the most games?

In [11]:
# Write your code here
results = steam_df.loc[(steam_df['behavior-name'] == 'purchase'), ['user-id', 'behavior-name']]
results_grupped = results.groupby('user-id').count()
results_grupped.head(10)
print(results_grupped.idxmax()[0])

62990992


**Task 9.** How many hours on average people played in "The Elder Scrolls V Skyrim"?

In [12]:
# Write your code here
result = steam_df.loc[((steam_df['game-title'] == 'The Elder Scrolls V Skyrim') & (steam_df['behavior-name'] == 'play')), ['value']]
result_sum = np.sum(result)
print(result_sum[0]/len(result))

104.71093057607091


**Task 10.** Which games were played the most (in terms of the number of hours played)? Display a DataFrame with the first 10 titles and respective numbers of hours.

In [13]:
# Write your code here
results = steam_df.loc[(steam_df['behavior-name'] == 'play'), ['game-title', 'value']]
results_grupped = results.groupby('game-title').sum().sort_values(by='value', ascending=False)
results_grupped.head(10)

value
game-title                                           
Dota 2                                       981684.6
Counter-Strike Global Offensive              322771.6
Team Fortress 2                              173673.3
Counter-Strike                               134261.1
Sid Meier's Civilization V                    99821.3
Counter-Strike Source                         96075.5
The Elder Scrolls V Skyrim                    70889.3
Garry's Mod                                   49725.3
Call of Duty Modern Warfare 2 - Multiplayer   42009.9
Left 4 Dead 2                                 33596.7

**Task 11.** Which games are the most consistently played (in terms of the average number of hours played)? Print a DataFrame with the first 10 titles and respective numbers of hours.

In [14]:
# Games - hours - sum
games_hours = steam_df.loc[(steam_df['behavior-name'] == 'play'), ['game-title', 'value']]
games_hours_groupped = games_hours.groupby('game-title').sum().reset_index()
#games_hours_groupped.head(10)

# Games - players - count
games_players = steam_df.loc[(steam_df['behavior-name'] == 'play'), ['game-title', 'user-id']]
# games_players_grupped = games_players.groupby('game-title').agg(users=('user-id', 'count')).reset_index()
games_players_grupped = games_players.groupby('game-title').agg({'user-id':'count'}).reset_index()
games_players_grupped.rename(columns={"user-id" : "users"}, inplace=True)
games_players_grupped.head(10)

# Games - players - hours - average
games_hours_average = games_hours_groupped
games_hours_average['value'] = games_hours_groupped['value'] / games_players_grupped['users']
games_hours_average = games_hours_average.sort_values(by='value', ascending=False).reset_index(drop=True)
print(games_hours_average[:10])

                          game-title        value
0            Eastside Hockey Manager  1295.000000
1  Baldur's Gate II Enhanced Edition   475.255556
2                    FIFA Manager 09   411.000000
3                          Perpetuum   400.975000
4              Football Manager 2014   391.984615
5              Football Manager 2012   390.453165
6              Football Manager 2010   375.048571
7              Football Manager 2011   365.703226
8                  Freaking Meatbags   331.000000
9        Out of the Park Baseball 16   330.400000


**Task 12\*\*.** Fix the above for the fact that 0 hours played is not listed, but only a purchase is recorded in such a case.

In [15]:
# Games - hours - sum
games_hours = steam_df.loc[(steam_df['behavior-name'] == 'play'), ['game-title', 'value']]
games_hours_grouped = games_hours.groupby('game-title').sum().reset_index()

# Games - players - count
games_players = steam_df.loc[(steam_df['behavior-name'] == 'play'), ['game-title', 'user-id']]
#games_players_grupped = games_players.groupby('game-title').agg(users=('user-id', 'count')).reset_index()
games_players_grouped = games_players.groupby('game-title').agg({'user-id':'count'}).reset_index()

# Games - players - count - purchase
games_players_purchase = steam_df.loc[(steam_df['behavior-name'] == 'purchase'), ['game-title', 'user-id']]

# Games - players - count - purchase only
games_players_diff = pd.concat([games_players, games_players_purchase]).drop_duplicates(keep=False)
games_players_diff_grouped = games_players_diff.groupby('game-title').agg({'user-id':'count'}).reset_index()

# Concat
games_players_concat = pd.concat([games_players_grouped, games_players_diff_grouped]).groupby('game-title').sum().reset_index()
games_players_concat.rename(columns={"user-id" : "users"}, inplace=True)

# Games - players - hours - average
games_hours_average = pd.merge(games_hours_grouped, games_players_concat, on='game-title')
games_hours_average['value'] = games_hours_average[['value', 'users']].apply(lambda x: float(x[0]) / float(x[1]), axis=1)
games_hours_average.drop(columns=['users'], inplace=True)
games_hours_average = games_hours_average.sort_values(by='value', ascending=False).reset_index(drop=True)
print(games_hours_average[:10])

                    game-title        value
0      Eastside Hockey Manager  1295.000000
1              FIFA Manager 09   411.000000
2                    Perpetuum   400.975000
3        Football Manager 2012   385.572500
4        Football Manager 2014   382.185000
5        Football Manager 2010   345.439474
6        Football Manager 2011   333.435294
7  Out of the Park Baseball 16   330.400000
8        Football Manager 2013   310.659615
9        Football Manager 2015   307.381013


**Task 13.** Apply the sigmoid function
$$f(x) = \frac{1}{1 + e^{-\frac{1}{100}x}}$$
to hours played and print a DataFrame with the first 10 rows from the entire Steam dataset after this change.

In [16]:
# Sigmoid function
def sigmoid(x):
    return 1 / (1 + np.exp(-(1/100) * x))

# Hours - sigmoid
hours_sigmoid = steam_df.copy()
hours_sigmoid['value'] = hours_sigmoid[['behavior-name', 'value']].apply(lambda x: sigmoid(x[1]) if x[0] == 'play' else x[1], axis=1)
print(hours_sigmoid[:10])


     user-id                  game-title behavior-name     value  zero
0  151603712  The Elder Scrolls V Skyrim      purchase  1.000000     0
1  151603712  The Elder Scrolls V Skyrim          play  0.938774     0
2  151603712                   Fallout 4      purchase  1.000000     0
3  151603712                   Fallout 4          play  0.704746     0
4  151603712                       Spore      purchase  1.000000     0
5  151603712                       Spore          play  0.537181     0
6  151603712           Fallout New Vegas      purchase  1.000000     0
7  151603712           Fallout New Vegas          play  0.530213     0
8  151603712               Left 4 Dead 2      purchase  1.000000     0
9  151603712               Left 4 Dead 2          play  0.522235     0


## Pandas tasks - MovieLens dataset

**Task 14\*.** Calculate popularity (by the number of users who watched a movie) of all genres. Print a DataFrame with two columns: genre, n_users, where n_users contains the number of users who watched a given genre. Sort all genres in descending order.

In [17]:
# Genres split into multiple rows
ml_copy = ml_df.copy()
ml_copy["genres"] = ml_copy["genres"].str.split("|")
ml_copy = ml_copy.explode('genres')

user_genres = pd.DataFrame(ml_copy[['userId', 'genres']])

# Count users per genres
user_genres_grouped = user_genres.groupby('genres').agg({'userId':'count'}).reset_index().sort_values(by='userId', ascending=False).reset_index(drop=True)
user_genres_grouped.rename(columns={"userId" : "n_users", "genres": "genre"}, inplace=True)
display(user_genres_grouped)

genre  n_users
0                Drama    41928
1               Comedy    39053
2               Action    30635
3             Thriller    26452
4            Adventure    24161
5              Romance    18124
6               Sci-Fi    17243
7                Crime    16681
8              Fantasy    11834
9             Children     9208
10             Mystery     7674
11              Horror     7291
12           Animation     6988
13                 War     4859
14                IMAX     4145
15             Musical     4138
16             Western     1930
17         Documentary     1219
18           Film-Noir      870
19  (no genres listed)       47

**Task 15\*.** Calculate average rating for all genres. Print a DataFrame with two columns: genre, rating, where rating contains the average rating for a given genre. Sort all genres in descending order.

In [18]:
# Genres split into multiple rows
ml_copy = ml_df.copy()
ml_copy["genres"] = ml_copy["genres"].str.split("|")
ml_copy = ml_copy.explode('genres')


rating_genre = pd.DataFrame(ml_copy[['genres', 'rating']])
rating_genre.rename(columns={"genres": "genre"}, inplace=True)


# Average rating per genre
avg_rating = rating_genre.groupby('genre').agg({'rating': 'mean'}).reset_index()
avg_rating = avg_rating.sort_values(by='rating', ascending=False).reset_index(drop=True)
print(avg_rating)

                 genre    rating
0            Film-Noir  3.920115
1                  War  3.808294
2          Documentary  3.797785
3                Crime  3.658294
4                Drama  3.656184
5              Mystery  3.632460
6            Animation  3.629937
7                 IMAX  3.618335
8              Western  3.583938
9              Musical  3.563678
10           Adventure  3.508609
11             Romance  3.506511
12            Thriller  3.493706
13             Fantasy  3.491001
14  (no genres listed)  3.489362
15              Sci-Fi  3.455721
16              Action  3.447984
17            Children  3.412956
18              Comedy  3.384721
19              Horror  3.258195


**Task 16.** Calculate each movie rating bias (deviation from the mean of all movies average rating). Print a DataFrame with the first 10 in the form: title, average rating, bias.

In [19]:
# Genres split into multiple rows
ml_copy = ml_df.copy()

title_rating = pd.DataFrame(ml_copy[['title', 'rating']])

# Average rating per movie
avg_rating = title_rating.groupby('title').agg({'rating': 'mean'}).reset_index()
avg_rating.rename(columns={"rating": "average_rating"}, inplace=True)

# Average rating per movie + bias
avg_rating_bias = avg_rating
avg_rating_bias['bias'] = avg_rating['average_rating'] - title_rating['rating'].mean()
print(avg_rating_bias[:10])

                                     title  average_rating      bias
0                               '71 (2014)        4.000000  0.498443
1  'Hellboy': The Seeds of Creation (2004)        4.000000  0.498443
2                   'Round Midnight (1986)        3.500000 -0.001557
3                      'Salem's Lot (2004)        5.000000  1.498443
4                'Til There Was You (1997)        4.000000  0.498443
5          'Tis the Season for Love (2015)        1.500000 -2.001557
6                       'burbs, The (1989)        3.176471 -0.325086
7                     'night Mother (1986)        3.000000 -0.501557
8              (500) Days of Summer (2009)        3.666667  0.165110
9           *batteries not included (1987)        3.285714 -0.215843


**Task 17.** Calculate each user rating bias (deviation from the mean of all users average rating). Print a DataFrame with the first 10 in the form: user_id, average rating, bias.

In [20]:
# Genres split into multiple rows
ml_copy = ml_df.copy()
display(ml_copy.head(10))

user_rating = pd.DataFrame(ml_copy[['userId', 'rating']])

# Average rating per movie
avg_rating = user_rating.groupby('userId').agg({'rating': 'mean'}).reset_index()
avg_rating.rename(columns={"rating": "average_rating"}, inplace=True)

# Average rating per movie + bias
avg_rating_bias = avg_rating
avg_rating_bias['bias'] = avg_rating['average_rating'] - user_rating['rating'].mean()
print(avg_rating_bias[:10])

userId  movieId  rating   timestamp             title  \
0       1        1     4.0   964982703  Toy Story (1995)   
1       5        1     4.0   847434962  Toy Story (1995)   
2       7        1     4.5  1106635946  Toy Story (1995)   
3      15        1     2.5  1510577970  Toy Story (1995)   
4      17        1     4.5  1305696483  Toy Story (1995)   
5      18        1     3.5  1455209816  Toy Story (1995)   
6      19        1     4.0   965705637  Toy Story (1995)   
7      21        1     3.5  1407618878  Toy Story (1995)   
8      27        1     3.0   962685262  Toy Story (1995)   
9      31        1     5.0   850466616  Toy Story (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1  Adventure|Animation|Children|Comedy|Fantasy  
2  Adventure|Animation|Children|Comedy|Fantasy  
3  Adventure|Animation|Children|Comedy|Fantasy  
4  Adventure|Animation|Children|Comedy|Fantasy  
5  Adventure|Animation|Children|Comedy|Fantasy  
6  Adventure|Animation|Children|Comedy|Fantasy  
7  Adventure|Animation|Children|Comedy|Fantasy  
8  Adventure|Animation|Children|Comedy|Fantasy  
9  Adventure|Animation|Children|Comedy|Fantasy

   userId  average_rating      bias
0       1        4.366379  0.864822
1       2        3.948276  0.446719
2       3        2.435897 -1.065660
3       4        3.555556  0.053999
4       5        3.636364  0.134807
5       6        3.493631 -0.007926
6       7        3.230263 -0.271294
7       8        3.574468  0.072911
8       9        3.260870 -0.240687
9      10        3.278571 -0.222986


**Task 18.** Randomly choose 10 movies and 10 users and print their interaction matrix in the form of a DataFrame with user_id as index and movie titles as columns. You can iterate over the DataFrame in this task. Alternatively, try using the DataFrame pivot and reindex methods and compare the execution time. Initialize the numpy random number generator with seed=4321.

In [21]:
# Pivot + reindex
user_ids = ml_df['userId'].unique()
movie_ids = ml_df['movieId'].unique()
rng = np.random.RandomState(seed=4321)
user_ids = sorted(list(rng.choice(user_ids, size=10)))
movie_ids = sorted(list(rng.choice(movie_ids, size=10)))

movies = list(ml_df['title'].loc[(ml_df['movieId'].isin(movie_ids))].drop_duplicates())

user_movie = ml_df.loc[((ml_df['userId'].isin(user_ids)) | (ml_df['movieId'].isin(movie_ids))),['userId', 'title']].pivot_table(index='userId', columns='title', aggfunc=len, fill_value=0.0)
user_movie.columns.name = None
user_movie.index.name = None
user_movie = user_movie.filter(items=user_ids, axis=0)
user_movie = user_movie.loc[:, x]
user_movie = user_movie.reindex(columns=['Father of the Bride (1950)', 'Matrix, The (1999)','Howards End (1992)', 'Thirteen Conversations About One Thing (a.k.a. 13 Conversations) (2001)', 'It Runs in the Family (2003)', 'I Love You to Death (1990)', 'Bedazzled (1967)', "I Don't Know How She Does It (2011)", 'Wind Rises, The (Kaze tachinu) (2013)',  'Night Guards (2016)'])
print(user_movie)



ValueError: Cannot index with multidimensional key

## Pandas + numpy tasks

**Task 19.** Create the entire interaction matrix (2D numpy array) for the MovieLens dataset. Print the submatrix of the first 10 rows and 10 columns.

In [22]:
user_movie = ml_df.loc[:, ['userId', 'movieId']].pivot_table(index='userId', columns='movieId', aggfunc=len, fill_value=0.0).to_numpy()
user_movie = np.vstack((np.zeros((1, user_movie.shape[1])), user_movie))
user_movie = np.concatenate([np.zeros((user_movie.shape[0], 1)), user_movie], axis=1)
print(user_movie[:10, :10])



[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


**Task 20.** Calculate the matrix of size (n_users, n_users) where at position (i, j) there is the number of movies watched both by user i and user j. Use a single matrix multiplication to obtain the result. Print the submatrix of first 10 rows and 10 columns.

In [ ]:
is_watched = ml_df.loc[:, ['userId', 'movieId']].pivot_table(index='userId', columns='movieId', aggfunc=len, fill_value=0.0).to_numpy()
user_count = np.matmul(is_watched, is_watched.T)
user_count = np.vstack((np.zeros((1, user_count.shape[1])), user_count))
user_count = np.concatenate([np.zeros((user_count.shape[0], 1)), user_count], axis=1)
print(user_count[:10, :10])


**Task 21.** Calculate the matrix of size (n_items, n_items) where at position (i, j) there is the number of users who watched both movie i and movie j. Use a single matrix multiplication to obtain the result. To prevent memory error use only the first 1000 items. Print the submatrix of first 10 rows and 10 columns.

In [27]:
user_movie = ml_df.loc[:, ['userId', 'movieId']].pivot_table(index='userId', columns='movieId', aggfunc=len, fill_value=0.0).to_numpy()
user_movie = np.vstack((np.zeros((1, user_movie.shape[1])), user_movie))
user_movie = np.concatenate([np.zeros((user_movie.shape[0], 1)), user_movie], axis=1)
is_watched = np.matmul(user_movie[:, :1000].T, user_movie[:, :1000])
print(is_watched[:10, :10])

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 215.  68.  32.   2.  32.  58.  32.   5.  12.]
 [  0.  68. 110.  26.   3.  22.  36.  18.   6.   3.]
 [  0.  32.  26.  52.   1.  19.  25.  19.   4.   9.]
 [  0.   2.   3.   1.   7.   3.   2.   6.   1.   0.]
 [  0.  32.  22.  19.   3.  49.  24.  23.   4.   9.]
 [  0.  58.  36.  25.   2.  24. 102.  22.   5.   9.]
 [  0.  32.  18.  19.   6.  23.  22.  54.   4.   5.]
 [  0.   5.   6.   4.   1.   4.   5.   4.   8.   0.]
 [  0.  12.   3.   9.   0.   9.   9.   5.   0.  16.]]


In [ ]:
arr = np.array([])
arr = np.hstack((arr, np.array([1,2,3])))
# arr is now [1,2,3]
print(arr.shape)