In [2]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Markdown, display, HTML

# Fix the dying kernel problem (only a problem in some installations - you can remove it, if it works without it)
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

# Numpy

For a detailed reference check out: https://numpy.org/doc/stable/reference/arrays.indexing.html.

## Creating numpy arrays

### Directly

In [3]:
a = np.array(
    [[1.0, 2.0, 3.0], 
     [4.0, 5.0, 6.0], 
     [7.0, 8.0, 9.0]]
)

print(a)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### From a list

In [4]:
a = [[1.0, 2.0, 3.0], 
     [4.0, 5.0, 6.0], 
     [7.0, 8.0, 9.0]]

print(a)
print()

a = np.array(a)

print(a)

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### From a list comprehension

In [5]:
a = [i**2 for i in range(10)]

print(a)
print()
print(np.array(a))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

[ 0  1  4  9 16 25 36 49 64 81]


### Ready-made functions in numpy

In [6]:
# All zeros
a = np.zeros((3, 4))
print("All zeros")
print(a)
print()

# All a chosen value
a = np.full((3, 4), 7.0)
print("All chosen value (variant 1)")
print(a)
print()

# or

a = np.zeros((3, 4))
a[:] = 7.0
print("All chosen value (variant 2)")
print(a)
print()

# Random integers

a = np.random.randint(low=0, high=10, size=(3, 2))
print("Random integers")
print(a)
print()

# Random values from the normal distribution (Gaussian)

print("Random values from the normal distribution")
a = np.random.normal(loc=0, scale=10, size=(3, 5))
print(a)
print()

# Random values with controlled seed

print("Random values from the normal distribution with controlled seed")
rng = np.random.RandomState(seed=1)
a = rng.normal(loc=0, scale=10, size=(3, 2))
print(a)

All zeros
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

All chosen value (variant 1)
[[7. 7. 7. 7.]
 [7. 7. 7. 7.]
 [7. 7. 7. 7.]]

All chosen value (variant 2)
[[7. 7. 7. 7.]
 [7. 7. 7. 7.]
 [7. 7. 7. 7.]]

Random integers
[[3 5]
 [1 4]
 [6 4]]

Random values from the normal distribution
[[ 24.70658622   2.1808814   -5.91450704 -13.16978226  11.86425425]
 [-10.7039526   -1.87114102   7.26154002  -3.86554024  21.88591899]
 [  3.51209252 -25.98572251  -2.62306173  -3.82316503   0.8836791 ]]

Random values from the normal distribution with controlled seed
[[ 16.24345364  -6.11756414]
 [ -5.28171752 -10.72968622]
 [  8.65407629 -23.01538697]]


## Slicing numpy arrays

### Slicing in 1D

To obtain only specific values from a numpy array one can use so called slicing. It has the form

**arr[low:high:step]**

where low is the lowest index to be retrieved, high is the lowest index not to be retrieved and step indicates that every step element will be taken.

In [7]:
a = [i**2 for i in range(10)]

print("Original: ", a)
print("First 5 elements:", a[:5])
print("Elements from index 3 to index 5:", a[3:6])
print("Last 3 elements (negative indexing):", a[-3:])
print("Printed in reverse order:", a[::-1])
print("Every second element:", a[::2])

Original:  [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
First 5 elements: [0, 1, 4, 9, 16]
Elements from index 3 to index 5: [9, 16, 25]
Last 3 elements (negative indexing): [49, 64, 81]
Printed in reverse order: [81, 64, 49, 36, 25, 16, 9, 4, 1, 0]
Every second element: [0, 4, 16, 36, 64]


### Slicing in 2D

In two dimensions it works similarly, just the slicing is separate for every dimension.

In [8]:
a = np.array([i for i in range(25)]).reshape(5, 5)

print("Original: ")
print(a)
print()
print("First 2 elements of the first 3 rows:")
print(a[:3, :2])
print()
print("Middle 3 elements from the middle 3 rows:")
print(a[1:4, 1:4])
print()
print("Bottom-right 3 by 3 submatrix (negative indexing):")
print(a[-3:, -3:])
print()
print("Reversed columns:")
print(a[:, ::-1])
print()

Original: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

First 2 elements of the first 3 rows:
[[ 0  1]
 [ 5  6]
 [10 11]]

Middle 3 elements from the middle 3 rows:
[[ 6  7  8]
 [11 12 13]
 [16 17 18]]

Bottom-right 3 by 3 submatrix (negative indexing):
[[12 13 14]
 [17 18 19]
 [22 23 24]]

Reversed columns:
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]
 [24 23 22 21 20]]



### Setting numpy array field values

In [9]:
a = np.array([i for i in range(25)]).reshape(5, 5)

print("Original: ")
print(a)
print()

a[1:4, 1:4] = 5.0

print("Middle values changed to 5")
print(a)
print()

b = np.array([i**2 - i for i in range(9)]).reshape(3, 3)

print("Second matrix")
print(b)
print()

a[1:4, 1:4] = b

print("Second matrix substituted into the middle of the first matrix")
print(a)

Original: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Middle values changed to 5
[[ 0  1  2  3  4]
 [ 5  5  5  5  9]
 [10  5  5  5 14]
 [15  5  5  5 19]
 [20 21 22 23 24]]

Second matrix
[[ 0  0  2]
 [ 6 12 20]
 [30 42 56]]

Second matrix substituted into the middle of the first matrix
[[ 0  1  2  3  4]
 [ 5  0  0  2  9]
 [10  6 12 20 14]
 [15 30 42 56 19]
 [20 21 22 23 24]]


## Operations on numpy arrays

It is important to remember that arithmetic operations on numpy arrays are always element-wise.

In [10]:
a = np.array([i**2 for i in range(9)]).reshape((3, 3))
print(a)
print()

b = np.array([i**0.5 for i in range(9)]).reshape((3, 3))
print(b)
print()

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]

[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]



### Element-wise sum

In [11]:
print(a + b)

[[ 0.          2.          5.41421356]
 [10.73205081 18.         27.23606798]
 [38.44948974 51.64575131 66.82842712]]


### Element-wise multiplication

In [12]:
print(a * b)

[[  0.           1.           5.65685425]
 [ 15.58845727  32.          55.90169944]
 [ 88.18163074 129.64181424 181.01933598]]


### Matrix multiplication

In [13]:
print(np.matmul(a, b))
print()

# Multiplication by the identity matrix (to check it works as expected)
id_matrix = [[1.0, 0.0, 0.0], 
             [0.0, 1.0, 0.0], 
             [0.0, 0.0, 1.0]]

print(np.matmul(id_matrix, a))

[[ 11.53000978  12.58300524  13.54977648]
 [ 88.95005649 107.14378278 119.21568782]
 [241.63783311 303.32808391 341.49835513]]

[[ 0.  1.  4.]
 [ 9. 16. 25.]
 [36. 49. 64.]]


### Calculating the mean

In [14]:
a = np.random.randint(low=0, high=10, size=(5))

print(a)
print()

print("Mean: ", np.sum(a) / len(a))

[2 6 5 3 7]

Mean:  4.6


### Calculating the mean of every row

In [15]:
a = np.random.randint(low=0, high=10, size=(5, 3))

print(a)
print()

print("Mean:", np.sum(a, axis=1) / a.shape[1])

print("Mean in the original matrix form:")
print((np.sum(a, axis=1) / a.shape[1]).reshape(-1, 1))  # -1 calculates the right size to use all elements

[[5 0 0]
 [7 2 2]
 [6 8 7]
 [5 4 6]
 [8 1 5]]

Mean: [1.66666667 3.66666667 7.         5.         4.66666667]
Mean in the original matrix form:
[[1.66666667]
 [3.66666667]
 [7.        ]
 [5.        ]
 [4.66666667]]


### More complex operations

In [16]:
a = [1.0, 2.0, 3.0]

print("Vector to power 2 (element-wise)")
print(np.power(a, 2))
print()
print("Euler number to the power a (element-wise)")
print(np.exp(a))
print()
print("An even more complex expression")
print((np.power(a, 2) + np.exp(a)) / np.sum(a))

Vector to power 2 (element-wise)
[1. 4. 9.]

Euler number to the power a (element-wise)
[ 2.71828183  7.3890561  20.08553692]

An even more complex expression
[0.61971364 1.89817602 4.84758949]


# Pandas

## Load datasets

- Steam (https://www.kaggle.com/tamber/steam-video-games)

- MovieLens (https://grouplens.org/datasets/movielens/)

In [17]:
steam_df = pd.read_csv(os.path.join("data", "steam", "steam-200k.csv"), 
                       names=['user-id', 'game-title', 'behavior-name', 'value', 'zero'])

ml_ratings_df = pd.read_csv(os.path.join("data", "movielens_small", "ratings.csv"))
ml_movies_df = pd.read_csv(os.path.join("data", "movielens_small", "movies.csv"))

## Peek into the datasets

In [18]:
steam_df.head(10)

user-id                  game-title behavior-name  value  zero
0  151603712  The Elder Scrolls V Skyrim      purchase    1.0     0
1  151603712  The Elder Scrolls V Skyrim          play  273.0     0
2  151603712                   Fallout 4      purchase    1.0     0
3  151603712                   Fallout 4          play   87.0     0
4  151603712                       Spore      purchase    1.0     0
5  151603712                       Spore          play   14.9     0
6  151603712           Fallout New Vegas      purchase    1.0     0
7  151603712           Fallout New Vegas          play   12.1     0
8  151603712               Left 4 Dead 2      purchase    1.0     0
9  151603712               Left 4 Dead 2          play    8.9     0

In [19]:
ml_ratings_df.head(10)

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931
5       1       70     3.0  964982400
6       1      101     5.0  964980868
7       1      110     4.0  964982176
8       1      151     5.0  964984041
9       1      157     5.0  964984100

In [20]:
ml_movies_df.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

## Merge both MovieLens DataFrames into one

In [21]:
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
ml_df.head(10)

userId  movieId  rating   timestamp             title  \
0       1        1     4.0   964982703  Toy Story (1995)   
1       5        1     4.0   847434962  Toy Story (1995)   
2       7        1     4.5  1106635946  Toy Story (1995)   
3      15        1     2.5  1510577970  Toy Story (1995)   
4      17        1     4.5  1305696483  Toy Story (1995)   
5      18        1     3.5  1455209816  Toy Story (1995)   
6      19        1     4.0   965705637  Toy Story (1995)   
7      21        1     3.5  1407618878  Toy Story (1995)   
8      27        1     3.0   962685262  Toy Story (1995)   
9      31        1     5.0   850466616  Toy Story (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1  Adventure|Animation|Children|Comedy|Fantasy  
2  Adventure|Animation|Children|Comedy|Fantasy  
3  Adventure|Animation|Children|Comedy|Fantasy  
4  Adventure|Animation|Children|Comedy|Fantasy  
5  Adventure|Animation|Children|Comedy|Fantasy  
6  Adventure|Animation|Children|Comedy|Fantasy  
7  Adventure|Animation|Children|Comedy|Fantasy  
8  Adventure|Animation|Children|Comedy|Fantasy  
9  Adventure|Animation|Children|Comedy|Fantasy

## Choosing rows or columns

### Choosing rows

In [21]:
steam_df_copy = steam_df.copy()
steam_df_copy.index = np.array(list(range(len(steam_df_copy)))) + 3
display(steam_df_copy.head(10))

# Choosing rows by index
chosen_df = steam_df_copy.loc[3:6]

print("Choosing rows by index")
display(chosen_df.head(10))

# Choosing rows by position
chosen_df = steam_df_copy.iloc[3:6]

print("Choosing rows by position")
display(chosen_df.head(10))

user-id                  game-title behavior-name  value  zero
3   151603712  The Elder Scrolls V Skyrim      purchase    1.0     0
4   151603712  The Elder Scrolls V Skyrim          play  273.0     0
5   151603712                   Fallout 4      purchase    1.0     0
6   151603712                   Fallout 4          play   87.0     0
7   151603712                       Spore      purchase    1.0     0
8   151603712                       Spore          play   14.9     0
9   151603712           Fallout New Vegas      purchase    1.0     0
10  151603712           Fallout New Vegas          play   12.1     0
11  151603712               Left 4 Dead 2      purchase    1.0     0
12  151603712               Left 4 Dead 2          play    8.9     0

Choosing rows by index


user-id                  game-title behavior-name  value  zero
3  151603712  The Elder Scrolls V Skyrim      purchase    1.0     0
4  151603712  The Elder Scrolls V Skyrim          play  273.0     0
5  151603712                   Fallout 4      purchase    1.0     0
6  151603712                   Fallout 4          play   87.0     0

Choosing rows by position


user-id game-title behavior-name  value  zero
6  151603712  Fallout 4          play   87.0     0
7  151603712      Spore      purchase    1.0     0
8  151603712      Spore          play   14.9     0

### Choosing a column

In [22]:
chosen_df = steam_df['game-title']

print("Type: {}".format(type(chosen_df)))
display(chosen_df.head(10))

Type: <class 'pandas.core.series.Series'>


0    The Elder Scrolls V Skyrim
1    The Elder Scrolls V Skyrim
2                     Fallout 4
3                     Fallout 4
4                         Spore
5                         Spore
6             Fallout New Vegas
7             Fallout New Vegas
8                 Left 4 Dead 2
9                 Left 4 Dead 2
Name: game-title, dtype: object

### Choosing several columns

In [23]:
chosen_df = steam_df[['user-id', 'game-title']]

display(chosen_df.head(10))

user-id                  game-title
0  151603712  The Elder Scrolls V Skyrim
1  151603712  The Elder Scrolls V Skyrim
2  151603712                   Fallout 4
3  151603712                   Fallout 4
4  151603712                       Spore
5  151603712                       Spore
6  151603712           Fallout New Vegas
7  151603712           Fallout New Vegas
8  151603712               Left 4 Dead 2
9  151603712               Left 4 Dead 2

### Splitting the dataset into training and test set

In [24]:
shuffle = np.array(list(range(len(steam_df))))

# alternatively

shuffle = np.arange(len(steam_df))

np.random.shuffle(shuffle)
shuffle = list(shuffle)
print("Shuffled range of indices")
print(shuffle[:20])
print()

train_test_split = 0.8
split_index = int(len(steam_df) * train_test_split)

training_set = steam_df.iloc[shuffle[:split_index]]
test_set = steam_df.iloc[shuffle[split_index:]]

display(training_set.head(10))

display(test_set.head(10))

Shuffled range of indices
[107252, 32752, 171401, 164824, 32810, 127879, 186390, 106393, 13384, 194929, 86266, 68978, 138065, 966, 148242, 114521, 62869, 65075, 145055, 71825]



user-id                             game-title behavior-name  value  \
107252   27279261    Plants vs. Zombies Game of the Year          play    4.3   
32752    86912006                     Arcane Saga Online      purchase    1.0   
171401  112849197        Counter-Strike Global Offensive          play  986.0   
164824   44314169          resident evil 4 / biohazard 4          play   21.0   
32810    86912006                             Dino D-Day      purchase    1.0   
127879   90033155                            Magic Duels      purchase    1.0   
186390   47457723          Icewind Dale Enhanced Edition          play    0.1   
106393   71510748               Amnesia The Dark Descent      purchase    1.0   
13384    32467994  Shadowrun Dragonfall - Director's Cut      purchase    1.0   
194929  244335912                           Block N Load      purchase    1.0   

        zero  
107252     0  
32752      0  
171401     0  
164824     0  
32810      0  
127879     0  
186390     0  
106393     0  
13384      0  
194929     0

user-id                           game-title behavior-name  value  \
73232   132014951                  Soccer Manager 2016          play    0.1   
139571    2753525                        Battlefield 2          play    0.3   
176095  104830836  Call of Duty Black Ops II - Zombies          play    0.2   
38854   110906645                         Just Cause 2      purchase    1.0   
31588   191477470  Call of Duty Black Ops II - Zombies      purchase    1.0   
191961   91807066                   Dragon Age Origins          play   14.9   
65940    64973908                       Ticket to Ride      purchase    1.0   
56351   122798021           Don't Starve Together Beta      purchase    1.0   
28952   116617462           Rome Total War - Alexander          play    0.5   
53344    46301758                       Frozen Synapse      purchase    1.0   

        zero  
73232      0  
139571     0  
176095     0  
38854      0  
31588      0  
191961     0  
65940      0  
56351      0  
28952      0  
53344      0

## Filtering

### Filtering columns

In [25]:
chosen_df = steam_df.loc[:, 'game-title']

print("Type: {}".format(type(chosen_df)))
display(chosen_df.head(10))
print()

chosen_df = steam_df.loc[:, ['game-title']]

print("Type: {}".format(type(chosen_df)))
display(chosen_df.head(10))
print()

chosen_df = steam_df.loc[:, ['user-id', 'game-title']]

print("Type: {}".format(type(chosen_df)))
display(chosen_df.head(10))

Type: <class 'pandas.core.series.Series'>


0    The Elder Scrolls V Skyrim
1    The Elder Scrolls V Skyrim
2                     Fallout 4
3                     Fallout 4
4                         Spore
5                         Spore
6             Fallout New Vegas
7             Fallout New Vegas
8                 Left 4 Dead 2
9                 Left 4 Dead 2
Name: game-title, dtype: object


Type: <class 'pandas.core.frame.DataFrame'>


game-title
0  The Elder Scrolls V Skyrim
1  The Elder Scrolls V Skyrim
2                   Fallout 4
3                   Fallout 4
4                       Spore
5                       Spore
6           Fallout New Vegas
7           Fallout New Vegas
8               Left 4 Dead 2
9               Left 4 Dead 2


Type: <class 'pandas.core.frame.DataFrame'>


user-id                  game-title
0  151603712  The Elder Scrolls V Skyrim
1  151603712  The Elder Scrolls V Skyrim
2  151603712                   Fallout 4
3  151603712                   Fallout 4
4  151603712                       Spore
5  151603712                       Spore
6  151603712           Fallout New Vegas
7  151603712           Fallout New Vegas
8  151603712               Left 4 Dead 2
9  151603712               Left 4 Dead 2

### Filtering rows

In [26]:
condition = steam_df['game-title'] == 'Fallout 4'

print(condition.head(10))

chosen_df = steam_df.loc[condition]

display(chosen_df.head(10))

0    False
1    False
2     True
3     True
4    False
5    False
6    False
7    False
8    False
9    False
Name: game-title, dtype: bool


user-id game-title behavior-name  value  zero
2     151603712  Fallout 4      purchase    1.0     0
3     151603712  Fallout 4          play   87.0     0
3187   87445402  Fallout 4      purchase    1.0     0
3188   87445402  Fallout 4          play   83.0     0
5683   25096601  Fallout 4      purchase    1.0     0
5684   25096601  Fallout 4          play    1.6     0
6219  211925330  Fallout 4      purchase    1.0     0
6220  211925330  Fallout 4          play  133.0     0
7300  115396529  Fallout 4      purchase    1.0     0
7301  115396529  Fallout 4          play   17.9     0

### Filtering rows and columns at once

In [27]:
chosen_df = steam_df.loc[(steam_df['game-title'] == 'Fallout 4') & (steam_df['behavior-name'] == 'play'), 
                         ['user-id', 'game-title', 'value']]

display(chosen_df.head(10))

user-id game-title  value
3      151603712  Fallout 4   87.0
3188    87445402  Fallout 4   83.0
5684    25096601  Fallout 4    1.6
6220   211925330  Fallout 4  133.0
7301   115396529  Fallout 4   17.9
7527     4834220  Fallout 4   19.8
7617    65229865  Fallout 4    0.5
7712    65958466  Fallout 4  123.0
9963    91800733  Fallout 4   63.0
10700   43913966  Fallout 4   65.0

## Simple operations on columns

### Multiply a column by 2

In [28]:
steam_df_copy = steam_df.copy()

display(steam_df_copy.head(10))

steam_df_copy['value'] = steam_df_copy['value'] * 2

# Command equivalent in effect but not efficiency
# steam_df_copy.loc[:, 'value'] = steam_df_copy['value'] * 2

display(steam_df_copy.head(10))

user-id                  game-title behavior-name  value  zero
0  151603712  The Elder Scrolls V Skyrim      purchase    1.0     0
1  151603712  The Elder Scrolls V Skyrim          play  273.0     0
2  151603712                   Fallout 4      purchase    1.0     0
3  151603712                   Fallout 4          play   87.0     0
4  151603712                       Spore      purchase    1.0     0
5  151603712                       Spore          play   14.9     0
6  151603712           Fallout New Vegas      purchase    1.0     0
7  151603712           Fallout New Vegas          play   12.1     0
8  151603712               Left 4 Dead 2      purchase    1.0     0
9  151603712               Left 4 Dead 2          play    8.9     0

user-id                  game-title behavior-name  value  zero
0  151603712  The Elder Scrolls V Skyrim      purchase    2.0     0
1  151603712  The Elder Scrolls V Skyrim          play  546.0     0
2  151603712                   Fallout 4      purchase    2.0     0
3  151603712                   Fallout 4          play  174.0     0
4  151603712                       Spore      purchase    2.0     0
5  151603712                       Spore          play   29.8     0
6  151603712           Fallout New Vegas      purchase    2.0     0
7  151603712           Fallout New Vegas          play   24.2     0
8  151603712               Left 4 Dead 2      purchase    2.0     0
9  151603712               Left 4 Dead 2          play   17.8     0

### Choose the first n letters of a string

In [2]:
ml_movies_df_copy = ml_movies_df.copy()

display(ml_movies_df_copy.head(10))

ml_movies_df_copy['title'] = ml_movies_df_copy['title'].str[:6]

display(ml_movies_df_copy.head(10))

NameError: name 'ml_movies_df' is not defined

### Take the mean of a column

In [30]:
# Option 1
print(steam_df['value'].mean())

# Option 2
print(np.mean(steam_df['value']))

17.874384000000003
17.874384000000003


### Simple operation on filtered data

In [31]:
steam_df_copy = steam_df.loc[((steam_df['game-title'] == 'Fallout 4') 
                              | (steam_df['game-title'] == 'The Elder Scrolls V Skyrim')) 
                             & (steam_df['behavior-name'] == 'play')].copy()

display(steam_df_copy.head(10))

condition = (steam_df_copy['game-title'] == 'Fallout 4') & (steam_df_copy['behavior-name'] == 'play')

steam_df_copy.loc[condition, 'value'] = steam_df_copy.loc[condition, 'value'] * 2

display(steam_df_copy.head(10))

user-id                  game-title behavior-name  value  zero
1     151603712  The Elder Scrolls V Skyrim          play  273.0     0
3     151603712                   Fallout 4          play   87.0     0
73     59945701  The Elder Scrolls V Skyrim          play   58.0     0
1066   92107940  The Elder Scrolls V Skyrim          play  110.0     0
1168  250006052  The Elder Scrolls V Skyrim          play  465.0     0
1388   11373749  The Elder Scrolls V Skyrim          play  220.0     0
2065   54103616  The Elder Scrolls V Skyrim          play   35.0     0
2569   56038151  The Elder Scrolls V Skyrim          play   14.6     0
3188   87445402                   Fallout 4          play   83.0     0
3233   94088853  The Elder Scrolls V Skyrim          play  320.0     0

user-id                  game-title behavior-name  value  zero
1     151603712  The Elder Scrolls V Skyrim          play  273.0     0
3     151603712                   Fallout 4          play  174.0     0
73     59945701  The Elder Scrolls V Skyrim          play   58.0     0
1066   92107940  The Elder Scrolls V Skyrim          play  110.0     0
1168  250006052  The Elder Scrolls V Skyrim          play  465.0     0
1388   11373749  The Elder Scrolls V Skyrim          play  220.0     0
2065   54103616  The Elder Scrolls V Skyrim          play   35.0     0
2569   56038151  The Elder Scrolls V Skyrim          play   14.6     0
3188   87445402                   Fallout 4          play  166.0     0
3233   94088853  The Elder Scrolls V Skyrim          play  320.0     0

## Advanced operations on columns

In [32]:
def scale_data(x):
    return np.log(1 + x)

def reduce_outliers(x):
    return min(x, 4)

steam_df_copy = steam_df.loc[steam_df['behavior-name'] == 'play'].copy()

display(steam_df_copy.head(10))

steam_df_copy['value'] = steam_df_copy['value'].apply(scale_data)
steam_df_copy['value'] = steam_df_copy['value'].apply(reduce_outliers)

display(steam_df_copy.head(10))

user-id                  game-title behavior-name  value  zero
1   151603712  The Elder Scrolls V Skyrim          play  273.0     0
3   151603712                   Fallout 4          play   87.0     0
5   151603712                       Spore          play   14.9     0
7   151603712           Fallout New Vegas          play   12.1     0
9   151603712               Left 4 Dead 2          play    8.9     0
11  151603712                    HuniePop          play    8.5     0
13  151603712               Path of Exile          play    8.1     0
15  151603712                 Poly Bridge          play    7.5     0
17  151603712                 Left 4 Dead          play    3.3     0
19  151603712             Team Fortress 2          play    2.8     0

user-id                  game-title behavior-name     value  zero
1   151603712  The Elder Scrolls V Skyrim          play  4.000000     0
3   151603712                   Fallout 4          play  4.000000     0
5   151603712                       Spore          play  2.766319     0
7   151603712           Fallout New Vegas          play  2.572612     0
9   151603712               Left 4 Dead 2          play  2.292535     0
11  151603712                    HuniePop          play  2.251292     0
13  151603712               Path of Exile          play  2.208274     0
15  151603712                 Poly Bridge          play  2.140066     0
17  151603712                 Left 4 Dead          play  1.458615     0
19  151603712             Team Fortress 2          play  1.335001     0

### The same apply operation can be achieved with the use of a lambda function

In [33]:
steam_df_copy = steam_df.loc[steam_df['behavior-name'] == 'play'].copy()

display(steam_df_copy.head(10))

steam_df_copy['value'] = steam_df_copy['value'].apply(lambda x: min(np.log(1 + x), 4))

display(steam_df_copy.head(10))

user-id                  game-title behavior-name  value  zero
1   151603712  The Elder Scrolls V Skyrim          play  273.0     0
3   151603712                   Fallout 4          play   87.0     0
5   151603712                       Spore          play   14.9     0
7   151603712           Fallout New Vegas          play   12.1     0
9   151603712               Left 4 Dead 2          play    8.9     0
11  151603712                    HuniePop          play    8.5     0
13  151603712               Path of Exile          play    8.1     0
15  151603712                 Poly Bridge          play    7.5     0
17  151603712                 Left 4 Dead          play    3.3     0
19  151603712             Team Fortress 2          play    2.8     0

user-id                  game-title behavior-name     value  zero
1   151603712  The Elder Scrolls V Skyrim          play  4.000000     0
3   151603712                   Fallout 4          play  4.000000     0
5   151603712                       Spore          play  2.766319     0
7   151603712           Fallout New Vegas          play  2.572612     0
9   151603712               Left 4 Dead 2          play  2.292535     0
11  151603712                    HuniePop          play  2.251292     0
13  151603712               Path of Exile          play  2.208274     0
15  151603712                 Poly Bridge          play  2.140066     0
17  151603712                 Left 4 Dead          play  1.458615     0
19  151603712             Team Fortress 2          play  1.335001     0

### Apply on two columns at once

In [34]:
steam_df_copy = steam_df.loc[steam_df['behavior-name'] == 'play'].copy()

display(steam_df_copy.head(10))

steam_df_copy['value_2'] = steam_df_copy['value'].apply(lambda x: min(np.log(1 + x), 4))

display(steam_df_copy.head(10))

steam_df_copy['value_3'] = steam_df_copy[['value', 'value_2']].apply(lambda x: x[0] * x[1], axis=1)

display(steam_df_copy.head(10))

user-id                  game-title behavior-name  value  zero
1   151603712  The Elder Scrolls V Skyrim          play  273.0     0
3   151603712                   Fallout 4          play   87.0     0
5   151603712                       Spore          play   14.9     0
7   151603712           Fallout New Vegas          play   12.1     0
9   151603712               Left 4 Dead 2          play    8.9     0
11  151603712                    HuniePop          play    8.5     0
13  151603712               Path of Exile          play    8.1     0
15  151603712                 Poly Bridge          play    7.5     0
17  151603712                 Left 4 Dead          play    3.3     0
19  151603712             Team Fortress 2          play    2.8     0

user-id                  game-title behavior-name  value  zero   value_2
1   151603712  The Elder Scrolls V Skyrim          play  273.0     0  4.000000
3   151603712                   Fallout 4          play   87.0     0  4.000000
5   151603712                       Spore          play   14.9     0  2.766319
7   151603712           Fallout New Vegas          play   12.1     0  2.572612
9   151603712               Left 4 Dead 2          play    8.9     0  2.292535
11  151603712                    HuniePop          play    8.5     0  2.251292
13  151603712               Path of Exile          play    8.1     0  2.208274
15  151603712                 Poly Bridge          play    7.5     0  2.140066
17  151603712                 Left 4 Dead          play    3.3     0  1.458615
19  151603712             Team Fortress 2          play    2.8     0  1.335001

user-id                  game-title behavior-name  value  zero  \
1   151603712  The Elder Scrolls V Skyrim          play  273.0     0   
3   151603712                   Fallout 4          play   87.0     0   
5   151603712                       Spore          play   14.9     0   
7   151603712           Fallout New Vegas          play   12.1     0   
9   151603712               Left 4 Dead 2          play    8.9     0   
11  151603712                    HuniePop          play    8.5     0   
13  151603712               Path of Exile          play    8.1     0   
15  151603712                 Poly Bridge          play    7.5     0   
17  151603712                 Left 4 Dead          play    3.3     0   
19  151603712             Team Fortress 2          play    2.8     0   

     value_2      value_3  
1   4.000000  1092.000000  
3   4.000000   348.000000  
5   2.766319    41.218155  
7   2.572612    31.128608  
9   2.292535    20.403559  
11  2.251292    19.135980  
13  2.208274    17.887023  
15  2.140066    16.050496  
17  1.458615     4.813430  
19  1.335001     3.738003

In [35]:
ml_movies_df_copy = ml_movies_df.copy()

display(ml_movies_df_copy.head(10))

ml_movies_df_copy['title|genres'] = ml_movies_df_copy[['title', 'genres']].apply(lambda x: x[0] + "|" + x[1], axis=1)

display(ml_movies_df_copy.head(10))

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   
5        6                         Heat (1995)   
6        7                      Sabrina (1995)   
7        8                 Tom and Huck (1995)   
8        9                 Sudden Death (1995)   
9       10                    GoldenEye (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy  
5                        Action|Crime|Thriller  
6                               Comedy|Romance  
7                           Adventure|Children  
8                                       Action  
9                    Action|Adventure|Thriller

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   
5        6                         Heat (1995)   
6        7                      Sabrina (1995)   
7        8                 Tom and Huck (1995)   
8        9                 Sudden Death (1995)   
9       10                    GoldenEye (1995)   

                                        genres  \
0  Adventure|Animation|Children|Comedy|Fantasy   
1                   Adventure|Children|Fantasy   
2                               Comedy|Romance   
3                         Comedy|Drama|Romance   
4                                       Comedy   
5                        Action|Crime|Thriller   
6                               Comedy|Romance   
7                           Adventure|Children   
8                                       Action   
9                    Action|Adventure|Thriller   

                                        title|genres  
0  Toy Story (1995)|Adventure|Animation|Children|...  
1          Jumanji (1995)|Adventure|Children|Fantasy  
2             Grumpier Old Men (1995)|Comedy|Romance  
3      Waiting to Exhale (1995)|Comedy|Drama|Romance  
4          Father of the Bride Part II (1995)|Comedy  
5                  Heat (1995)|Action|Crime|Thriller  
6                      Sabrina (1995)|Comedy|Romance  
7             Tom and Huck (1995)|Adventure|Children  
8                         Sudden Death (1995)|Action  
9         GoldenEye (1995)|Action|Adventure|Thriller

## Grouping and aggregating

### Find the most popular games (in terms of purchases)

In [36]:
steam_grouped = steam_df.loc[steam_df['behavior-name'] == 'purchase', ['game-title', 'value']]
steam_grouped = steam_grouped.groupby('game-title').sum()
steam_grouped = steam_grouped.sort_values(by='value', ascending=False).reset_index()

display(steam_grouped.head(10))

game-title   value
0                           Dota 2  4841.0
1                  Team Fortress 2  2323.0
2                         Unturned  1563.0
3  Counter-Strike Global Offensive  1412.0
4           Half-Life 2 Lost Coast   981.0
5            Counter-Strike Source   978.0
6                    Left 4 Dead 2   951.0
7                   Counter-Strike   856.0
8                         Warframe   847.0
9           Half-Life 2 Deathmatch   823.0

### Alternative way of aggregating

In [37]:
steam_grouped = steam_df.loc[steam_df['behavior-name'] == 'purchase', ['game-title', 'value']]
steam_grouped = steam_grouped.groupby('game-title').agg({'value': 'sum'})
# Alternatively
# steam_grouped = steam_grouped.groupby('game-title').agg({'value': sum})
# Alternatively
# steam_grouped = steam_grouped.groupby('game-title').agg({'value': lambda x: np.sum(x)})
steam_grouped = steam_grouped.sort_values(by='value', ascending=False).reset_index()

display(steam_grouped.head(10))

game-title   value
0                           Dota 2  4841.0
1                  Team Fortress 2  2323.0
2                         Unturned  1563.0
3  Counter-Strike Global Offensive  1412.0
4           Half-Life 2 Lost Coast   981.0
5            Counter-Strike Source   978.0
6                    Left 4 Dead 2   951.0
7                   Counter-Strike   856.0
8                         Warframe   847.0
9           Half-Life 2 Deathmatch   823.0

## Iterating over a DataFrame (if possible, use column operations instead)

In [38]:
i = 0
for idx, row in steam_df.iterrows():
    print("[{}, {}, {}]".format(row['user-id'], row['game-title'], row['behavior-name']))
    i += 1
    if i == 10:
        break

[151603712, The Elder Scrolls V Skyrim, purchase]
[151603712, The Elder Scrolls V Skyrim, play]
[151603712, Fallout 4, purchase]
[151603712, Fallout 4, play]
[151603712, Spore, purchase]
[151603712, Spore, play]
[151603712, Fallout New Vegas, purchase]
[151603712, Fallout New Vegas, play]
[151603712, Left 4 Dead 2, purchase]
[151603712, Left 4 Dead 2, play]
